### ISSUE TITLE
Provide more descriptive documentation on operations

### ISSUE THREAD

**Issue by Haishi2016** [microsoft/QuantumLibraries#134]
There's basically no descriptions on what each operation does. Sure, based on the operation name some experienced developer can infer/guess what it does, but it's pretty hard for a beginner to make sense of it. As an example, look at the documentation on "S" operation.

**Comment by cgranade** [comment]
For the example of the [`S` operation](https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.intrinsic.s), the API reference provides the matrix description of the operation:

![image](https://user-images.githubusercontent.com/31516/61072166-98452b00-a3c7-11e9-8a1c-0d871a41171e.png)

This matrix form is a complete description of what the `S` operation does, but I definitely take the point that that is a bit hard for a beginner to make sense of. At the moment, the explanation of matrix notation for what the different operations each do is largely in the [conceptual documentation about linear algebra](https://docs.microsoft.com/quantum/concepts/vectors-and-matrices), but that doesn't have much in the way of Q# examples to make it easier to understand how the reference documentation works.

Perhaps what might make the most sense is to open new issues to track the improvement of the conceptual articles and the list of other resources for beginners. I'll go on and do that, thanks for filing the issue!

**Comment by bromeg** [comment]
These types of operations are similar to calls to cos, sin, etc. We do not think reference documentation is the right place to explain what 'S' does, just like we wouldn't use reference docs to explain what cos is. However, we do think it will be valuable to add additional examples/tutorials to make these operations more approachable. We captured that in issue #113.
