### ISSUE TITLE
Single Type for artithmetics in Q#

### ISSUE THREAD

**Issue by griffonsjla** [microsoft/QuantumLibraries#136]
Hello everybody!
I am not an expert, and I have been (unsuccessfully) trying to multiply two real numbers using the QuantumSimulator.
Simulation works fine using Toffolis, but I want to use the full qubit, here is the code:

	operation Multab(fstNbr: Double, scdNbr: Double) : Double {
	    let numBits = 3;
	    mutable result = 0.0;
		using ((register1, register2, carry) = (Qubit[numBits], Qubit[numBits], Qubit[numBits])) {
			let qa = FixedPoint(1,register1);
			let qb = FixedPoint(1,register2);
			let qab = FixedPoint(1,carry);
        
			// initialize the quantum numbers:
			PrepareFxP(fstNbr, qa);
			PrepareFxP(scdNbr, qb);
			PrepareFxP(0.0, qab);
        
			// perform product
			MultiplyFxP(qa, qb, qab);

                       set result = MeasureFxP(qab);
                       ResetAll(register1 + register2 + carry);
		}

Using 3 bits, the result is 0 for any numbers, reasonable for 3 bits, but if I try 4 bits, simulation fails,
My point is: having available the Single precision type, avoiding use of Double type, could help to solve this issue? 
Thanks a lot!

**Comment by cgranade** [comment]
Thanks for the report, @griffonsjla, we really appreciate the feedback. If apologize, though, that I'm not sure I entirely understand your questions. You mentioned that your program works well on the Toffoli simulator target machine, but fails on the quantum simulator target machine, is that correct? How does the simulation fail when using 4-qubit registers?

In any case, I don't believe that single-precision versus double-precision would help in this case, as double-precision refers to the representation used by _classical_ registers. In the program you provided, the quantum registers are represented by the `FixedPoint` type on an arbitrary number of qubits (`numBits` in your example).

**Comment by bromeg** [comment]
We will be closing this for now. If additional info can be provided please re-open the issue.
