### ISSUE TITLE
A variant of Microsoft.Quantum.Canon.ApplyWith where inner and outer operations take different arguments

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/QuantumLibraries#141]
**Is your feature request related to a problem? Please describe.**
The pattern described by `Microsoft.Quantum.Canon.ApplyWith` is quite common in quantum algorithm, and there are many common cases where inner and outer operations take different arguments. 

**Describe the solution you'd like**
I would like to add `Microsoft.Quantum.Canon.ApplyWith2` and its variants (`A, CA, C`) with the following signature:
```qsharp
operation ApplyWith2<'T,'U>( 
    (outer: ('T => Unit is Adj), outArg : 'T),
    (inner : ('U => Unit), inArg : 'U), 
    ) : Unit 
// Called as: 
ApplyWith2( (op1,qubi1), (op2,(qubit1, qubit2)) );
// Note that (op2,(qubit1, qubit2)) looks very close to usual call op2(qubit1, qubit2)
```

**Describe alternatives you've considered**
An alternative is to introduce 
```
operation HoldOperation<'T> ( op : ('T => Unit), arg : 'T, dummy : Unit ) : Unit {
	op(arg);
}
```
and use partial application to make operations with different arguments to have type `Unit => Unit`.  
This might have bigger run-time overhead and is a bit more cumbersome to use.

**Additional context**
I am happy to make a PR with extended version of `ApplyWith`. I would appreciate Q# community and in particular @cgranade suggesting a better name  for `ApplyWith2`.

**Comment by bettinaheim** [comment]
FYI, I am currently working on adding support for a conjugate-with statement that should largely provide the functionality - aside from enabling partial applications thereof and the like: https://github.com/microsoft/qsharp-compiler/issues/43.

**Comment by vadym-kl** [comment]
@bettinaheim, do you think this enhancement should be abandoned, or will it still be useful to have this is `Microsoft.Quantum.Canon` ? I feel like it still might be useful.

**Comment by guenp** [comment]
Hi @vadym-kl, thank you for this suggestion! We have discussed in the API review and have come to the following conclusions;

- the language since has been expanded with support for [conjugations](https://docs.microsoft.com/en-us/quantum/user-guide/language/statements/conjugations) (`within`/`apply`)
- the `HoldOperation` operation you suggest has been implemented with the `Delay` operation and `Delayed` function

We therefore think there are sufficient options for covering this feature using the existing tools; for instance, one could implement:
```
operation outer(qubit1: Qubit): Unit is Adj {
    // my outer op
}

operation inner(qubit1: Qubit, qubit2: Qubit): Unit {
    // my inner op
}

within {
    outer(qubit1);
} apply {
    inner(qubit1, qubit2);
}
```

Please let me know if this resolves this issue for you, if yes then we can close it. Thanks!

**Comment by vadym-kl** [comment]
@guenp , sounds good to me.

**Comment by bettinaheim** [comment]
@guenp Do you have the promised link the the API review notes?
@vadym-kl Are you good with closing this, or was there a specific reason you reopened it?

**Comment by cgranade** [comment]
@bettinaheim: Please see notes at https://github.com/microsoft/QuantumLibraries/blob/09668fbac88b95e506fd9873658d65c7d92dd55f/Design/meetings/2021/api-design-2021-01-07.md#applywith2.

**Comment by cgranade** [comment]
Closing as per Jan 2021 review; please feel free to reopen again if you would like to revisit the proposal. Thank you!
