### ISSUE TITLE
ApplyIfOneCA and ApplyIfZeroCA have wrong signatures

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/QuantumLibraries#155]
**Describe the bug**
[AplyIfOneCA](https://github.com/microsoft/QuantumLibraries/blob/4490ba8295e18d2ddbfb42dee584c6fcb3101c45/Standard/src/Canon/Combinators/ApplyIf.qs#L292) and [ApplyIfZeroCA](https://github.com/microsoft/QuantumLibraries/blob/4490ba8295e18d2ddbfb42dee584c6fcb3101c45/Standard/src/Canon/Combinators/ApplyIf.qs#L412) have wrong signatures

**To Reproduce**
Current signatures are: 
```
operation ApplyIfZeroCA<'T> (result : Result, (op : ('T => Unit is Adj), target : 'T)) : Unit is Adj 
operation ApplyIfOneCA<'T> (result : Result, (op : ('T => Unit is Adj), target : 'T)) : Unit is Adj 
```

**Expected behavior**
The signatures must be
```
operation ApplyIfZeroCA<'T> (result : Result, (op : ('T => Unit is Adj + Ctl), target : 'T)) : Unit is Adj + Ctl 
operation ApplyIfOneCA<'T> (result : Result, (op : ('T => Unit is Adj + Ctl), target : 'T)) : Unit is Adj + Ctl
```

**Comment by christopherkang** [comment]
This has been fixed, right? If so, let's close the issue. :)

**Comment by cgranade** [comment]
Thanks for the catch, closing now!
