### ISSUE TITLE
Enable Source Link

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/QuantumLibraries#159]
## Please describe what you would like the feature to accomplish.
I would like to see source code and debug symbol information when debugging code that uses NuGet packages from this repository.

## Describe the solution you'd like 
It would be nice to enable [SourceLink](https://github.com/dotnet/sourcelink) support.

## Describe alternatives you've considered 
I am not aware of alternatives to [SourceLink](https://github.com/dotnet/sourcelink) that are cross-platform.

**Comment by cgranade** [comment]
Resolved by #160.
