### ISSUE TITLE
Various library functions and operations do not follow style guide.

### ISSUE THREAD

**Issue by cgranade** [microsoft/QuantumLibraries#162]
**Describe the bug**
The name `RandomInt` suggests a function, not an operation, but sampling a pseudorandom number generator or a QRNG is not deterministic. Thus, the names of these operations should be changed to `SampleRandomInt` and similar with appropriate deprecation warnings added.

**Comment by cgranade** [comment]
As another example of a callable that still needs to be updated, [`DecomposeIntoTimeSteps`](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.canon.decomposeintotimestepsca?view=qsharp-preview) is a function, and should likely be renamed to `DecomposedIntoTimeSteps`. Renaming the issue and  broadening scope to include more examples.

**Comment by guenp** [comment]
We will close this in favor of more narrowed-down issues such as https://github.com/microsoft/QuantumLibraries/issues/158. If we need to refactor more namespaces, we will create more namespace-specific issues.
