### ISSUE TITLE
Operations to repeat a call 𝑛 times

### ISSUE THREAD

**Issue by cgranade** [microsoft/QuantumLibraries#245]
**Is your feature request related to a problem? Please describe.**
Following offline discussions with @alan-geller and @tcNickolas, and following a suggestion from @crazy4pi314, it would be nice to have operations which repeatedly apply another operation 𝑛 times.

**Describe the solution you'd like**
Following the example of R, this feature request would introduce five new operations into the Microsoft.Quantum.Standard package:

```Q#
namespace Microsoft.Quantum.Canon {
    operation Repeat<'TInput>(op : ('TInput => Unit), nTimes : Int, input : 'TInput) : Unit { ... }
    operation RepeatA<'TInput>(op : ('TInput => Unit is Adj), nTimes : Int, input : 'TInput) : Unit is Adj { ... }
    operation RepeatC<'TInput>(op : ('TInput => Unit is Ctl), nTimes : Int, input : 'TInput) : Unit is Ctl { ... }
    operation RepeatCA<'TInput>(op : ('TInput => Unit is Adj + Ctl), nTimes : Int, input : 'TInput) : Unit is Adj + Ctl { ... }
}

namespace Microsoft.Quantum.Arrays {
    operation Replicate<'TInput, 'TOutput>(op : ('TInput => 'TOutput), nTimes : Int, input : 'TInput) : 'TOutput[] { ... }
}
```

**Describe alternatives you've considered**
The following currently work in place of the Repeat and Replicate operations proposed above, but are unwieldy:

```Q#
ApplyToEach(Delay(op, input, _), ConstantArray(nTimes, ()));
ForEach(Delay(op, input, _), ConstantArray(nTimes, ()));
```

Alternative names considered for `Replicate`:

- `Repeat`: doesn't make clear that outputs are collected.
- `Sample`: may work, but is too close to Microsoft.Quantum.MachineLearning.Sampled; the noun-vs-verb distinction is not held to uniformly enough to make the distinction clear.
- `DrawSample`: may work, but verb "draw" is a bit esoteric.
- `DoNTimes`: similar to `Repeat`, doesn't make clear that outputs are collected.
- `Collect`: doesn't make clear what is being collected.
- `RepeatAndCollect`: somewhat clear, but unnecessarily verbose

**Comment by tcNickolas** [comment]
`Replicate` doesn't make clear that the outputs are going to be distinct (replica is a copy), so it reads as another version of `ConstantArray`

**Comment by cgranade** [comment]
In the case of R, it's used to indicate replicating a process. The same thing could very reasonably be said of `Repeat` as well.

**Comment by cgranade** [comment]
Given that an operation from `() => 'T` can be used to model a distribution, let me revise the above to reflect that usecase:

```Q#
namespace Microsoft.Quantum.Canon {
    operation Repeat<'TInput>(op : ('TInput => Unit), nTimes : Int, input : 'TInput) : Unit { ... }
    operation RepeatA<'TInput>(op : ('TInput => Unit is Adj), nTimes : Int, input : 'TInput) : Unit is Adj { ... }
    operation RepeatC<'TInput>(op : ('TInput => Unit is Ctl), nTimes : Int, input : 'TInput) : Unit is Ctl { ... }
    operation RepeatCA<'TInput>(op : ('TInput => Unit is Adj + Ctl), nTimes : Int, input : 'TInput) : Unit is Adj + Ctl { ... }
}

namespace Microsoft.Quantum.Arrays {
    operation DrawMany<'TInput, 'TOutput>(op : ('TInput => 'TOutput), nSamples : Int, input : 'TInput) : 'TOutput[] { ... }
}
```

That would also go well with improved random number generation support, and could be used to provide a new Microsoft.Quantum.Random namespace:

```Q#
namespace Microsoft.Quantum.Random {
    newtype ContinuousDistribution = (Sample : Unit => Double);
    newtype DiscreteDistribution = (Sample : Unit => Int);
    function ContinuousUniformDistribution(min : Double, max : Double) : ContinuousDistribution;
    function DiscreteUniformDistribution(min : Int, max : Int) : DiscreteDistribution;
    function CategoricalDistribution(props : Double[]) : DiscreteDistribution;
    function StandardNormalDistribution() : ContinuousDistribution;
    function NormalDistribution(mean : Double, variance : Double) : ContinuousDistribution;
    function TransformedContinuousDistribution(transform : Double -> Double, distribution : ContinuousDistribution) : Distribution;
    operation MaybeChooseElement<'T>(data : 'T[], indexDistribution : DiscreteDistribution) : (Bool, 'T);
    operation SampleBinomialTrial(successProbability : Double) : Bool;
}
```

(As a side note, I'd love to use `Maybe` from https://github.com/microsoft/qsharp-compiler/issues/406 for `MaybeChooseElement`.)

**Comment by cgranade** [comment]
Adding @msoeken for discussion and API review.

**Comment by msoeken** [comment]
I prefer the names `Repeat` (+ variants) and `DrawMany`. Particularly, calling the argument `nSamples` in `DrawMany` made it immediately clear to me what the difference is to `Repeat`. And I agree that this opens the possibility to more interesting API in the Random namespace. Do we already discuss the API for that in this issue, or open another one once we have `Repeat` and `DrawMany` in the libraries?

**Comment by cgranade** [comment]
Thanks for your input, @msoeken! As for splitting the issue or not, I think the Microsoft.Quantum.Random API would likely need to live in qsharp-runtime repo due to dependency ordering (some subset would need to be intrinsic), despite being a Q# library. Thus, my suggestion would be to proceed with adding `Repeat` and `DrawMany` for now, and to open a new issue on qsharp-runtime to implement the proposed API for Microsoft.Quantum.Random.
