### ISSUE TITLE
broken link at Readme.md

### ISSUE THREAD

**Issue by birbilis** [Microsoft/QuantumLibraries#26]
Readme.md mentions one can check Chemistry folder of Quantum repository, but there's no such folder there (broken link)

Can find that folder at
https://github.com/Microsoft/Quantum/tree/release/v0.3.1811.203/Chemistry
(some older release I suppose)

Had that code moved to other repo?

**Comment by tcNickolas** [comment]
I think this was an artifact of 0.3 release which resided in a separate branch for quite a while before being merged into master branch on Feb 1. Right now chemistry samples can be found at https://github.com/Microsoft/Quantum/tree/master/Chemistry as the link points.

Could you please double-check that this is fixed?

**Comment by anpaz-msft** [comment]
v0.3.1811.203 was the `main` branch of the Microsoft/Quantum repository for a while until we were able to update all the samples with all the breaking changes between 0.2 to 0.3.
This work is now complete and `master` is up to date. as @tcNickolas  pointed out, https://github.com/Microsoft/Quantum/tree/master/Chemistry is now good to go.
