### ISSUE TITLE
Random - Should this be an operation?

### ISSUE THREAD

**Issue by christopherkang** [microsoft/QuantumLibraries#263]
**Is your feature request related to a problem? Please describe.**
The Random method (https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.random) is described as an operation, but has functionality that would characterize it as an operation. 

**Describe the solution you'd like**
It would be nice to have this implemented as a function. 

**Describe alternatives you've considered**
It's not hard to change the functions that use this to operations, but I'm a bit confused by the intuition to label the Random methods as operations. 

**Additional context**

**Comment by cgranade** [comment]
Thanks for the report, we appreciate the feedback. In this case, however, we really can't make random number sampling into functions; sampling random number generators is inherently non-deterministic, such that it can't be expressed as a function without causing problems for adjointability. For example, consider the following operation:

```
operation RotateByRandomAngle(target : Qubit) : Unit is Adj + Ctl {
     let angle = RandomAngle(); // ok if RandomAngleis a function
     Rz(angle, target);
}
```

This operation breaks the invariant that adjoints represent inverse operations, as `RotateByRandomAngle(target); Adjoint RotateByRandomAngle(target);` fails to be an identity operation in generality, as the value of `angle` can be different in both calls to `RotateByRandomAngle`.

Put differently, marking a callable as a function represents the invariant that if the input value passed to the function is the same, then the output will also be the same. For example, `Sin(PI() / 3.0)` is another name for a particular floating point number, and remains the same no matter how many times `Sin` is called. The way I like to think of it is that functions _are_ things, while operations _do_ things (hence the naming convention of using nouns for functions and verbs for operations).

Hopefully that helps, please let me know if there's anything else we can add. Thanks again for your report!

**Comment by christopherkang** [comment]
Thanks, @cgranade! That makes a lot of sense. I'd like to clarify the workflow for operations that rely upon some sort of probabilistic input to determine their behavior.

It seems like the operation should contain a field for parameters, and the same set of randomized parameters should be passed every time the operation is called, thus allowing the operation to be adjointable/controllable. Is that accurate? Or are there better ways to make probabilistic operations?

**Comment by cgranade** [comment]
> Thanks, @cgranade! That makes a lot of sense.

No worries, happy to help, and thanks again for your question and your report!

> I'd like to clarify the workflow for operations that rely upon some sort of probabilistic input to determine their behavior.
> 
> It seems like the operation should contain a field for parameters, and the same set of randomized parameters should be passed every time the operation is called, thus allowing the operation to be adjointable/controllable. Is that accurate? Or are there better ways to make probabilistic operations?

If I understand correctly, I think that definitely makes sense as a strategy. Indeed, in the contrived example I wrote above, you could make the rotation operation adjointable again by taking the random angle as an input instead of directly sampling a random number from within the rotation operation. That way, you can safely pass the same random angle to both the forward and adjoint calls to the operation to test the operation. A probabilistic unit test, for instance, may generate a test case randomly, and then use that test case as input to adjointable operations.

**Comment by christopherkang** [comment]
Fantastic! Great to know.
