### ISSUE TITLE
LocalUnivariateMinimum makes needlessly many calls

### ISSUE THREAD

**Issue by ollpu** [microsoft/QuantumLibraries#286]
The [implementation of LocalUnivariateMinimum](https://github.com/microsoft/QuantumLibraries/blob/master/Standard/src/Optimization/Univariate.qs#L61) makes two function calls to `fn` in each step instead of one.

The total amount of calls is currently about 2log<sub>φ</sub>(|bounds|/tolerance).

The point of using golden interval or golden section search is to avoid making two queries on each step. If the probe points didn't need to be optimized for this, they could be chosen arbitrarily close to each other in the middle for a query count of around 2log<sub>2</sub>(|bounds|/tolerance) (which would be ~1.388 times better than the current implementation).

By choosing the probe points in a golden section, one of them from the last iteration can be reused.

If the current bounds are [L<sub>0</sub>, R<sub>0</sub>], probes will be chosen at

A<sub>0</sub> = R<sub>0</sub> - (R<sub>0</sub> - L<sub>0</sub>)/φ and
B<sub>0</sub> = L<sub>0</sub> + (R<sub>0</sub> - L<sub>0</sub>)/φ.

The next bounds [L<sub>1</sub>, R<sub>1</sub>] are either [L<sub>0</sub>, B<sub>0</sub>] or [A<sub>0</sub>, R<sub>0</sub>].
In the former case, probe B<sub>1</sub> can be reused:

B<sub>1</sub> = L<sub>1</sub> + (R<sub>1</sub> - L<sub>1</sub>)/φ = L<sub>0</sub> + (B<sub>0</sub> - L<sub>0</sub>)/φ = L<sub>0</sub> + (L<sub>0</sub> + (R<sub>0</sub> - L<sub>0</sub>)/φ - L<sub>0</sub>)/φ
= L<sub>0</sub> + ((R<sub>0</sub> - L<sub>0</sub>)*(φ-1))/φ
= R<sub>0</sub> - (R<sub>0</sub> - L<sub>0</sub>)/φ
= A<sub>0</sub>

Similarly, probe A<sub>1</sub> = B<sub>0</sub> can be reused in the latter case.

This reduces the amount of calls to `fn` to 1+log<sub>φ</sub>(|bounds|/tolerance).

**Comment by guenp** [comment]
@ollpu, thank you for pointing out this improvement. Would you be interested in helping us implement this?

**Comment by ollpu** [comment]
Sure, I can try draft a PR in a couple weeks.

**Comment by guenp** [comment]
@ollpu, great, thanks a lot! If you have any questions or want to bounce ideas, please do reach out. You can ping me on this thread or reach out via a DM on the [Q# Community Slack](https://join.slack.com/t/qsharp-community/shared_invite/zt-fnsl4u42-u21wdJRzlLF9oAqYTDDtwA).
