### ISSUE TITLE
DumpOperation is not adjointable or controllable

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumLibraries#336]
**Describe the bug**
`DumpOperation` (an extremely useful tool!) cannot be called from an operation that asks for all its operations to be adjointable or controllable (for example, an operation specified as `is Adj+Ctl`). This seems rather odd, since the docs say that it doesn't have an effect observable from Q#, so it would make sense to it behave like `DumpMachine` which can be called from any Q# code.

**To Reproduce**

I ran the following snippet from Q# Jupyter Notebook:
```qsharp
open Microsoft.Quantum.Diagnostics;

operation DumpCnot() : Unit is Adj+Ctl {
    DumpOperation(2, ApplyToFirstTwoQubitsCA(CNOT, _));
}
```

I got the following error:
`c:\snippet_.qs(4,5): error QS6312: The called operation does not support the necessary functor(s) for the requested auto-generation of a specialization. Missing support for functor(s) Adjoint, Controlled.`

**Expected behavior**
Operation compiled successfully and subsequent `%simulate DumpCnot` offer me a dump of CNOT.

**System information**
 - IQ# version 0.12.20092803

**Comment by cgranade** [comment]
Good catch, thanks for pointing that out, @tcNickolas. We should definitely modify that to be adjointable and controllable, matching the behavior of other Dump* instructions.

**Comment by Pallavi-mp** [comment]
@cgranade I had a go at this, and I have the fix for it ready. Can I go ahead and create a pull request if nobody has picked it up yet?

**Comment by cgranade** [comment]
@Pallavi-mp: I'm not aware of anyone else picking this up yet, please go on and open a PR. Thank you for your contribution!
