### ISSUE TITLE
Update unit tests to use @Test attribute, descriptive names

### ISSUE THREAD

**Issue by cgranade** [microsoft/QuantumLibraries#340]
**Is your feature request related to a problem? Please describe.**
Many of the unit tests in the Q# standard and domain-specific libraries predate the existence of the new [`@Test()` attribute](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.diagnostics.test), and should be updated. The legacy method of discovering tests (namely, functions and operations in allow-listed namespaces whose names end in "Test") is more difficult to use with functionality such as test filtering and reporting, and doesn't allow for running tests on a variety of simulator targets.

For example, the [existing `ReverseTest` function](https://github.com/microsoft/QuantumLibraries/blob/main/Standard/tests/ArrayTests.qs#L120) is written as:

```Q#
function ReverseTest () : Unit {
    let array = [1, 2, 3];
    Ignore(Mapped(EqualityFactI(_, _, $"Reversed failed."), Zipped([3, 2, 1], Reversed(array))));
}
```

Using the new `@Test` attribute would allow for giving this test a more descriptive name that helps when reading test failure logs:

```
open Microsoft.Quantum.Diagnostics;

@Test("QuantumSimulator")
function ReversedIsCorrect() : Unit {
    AllEqualityFactI(Reversed([1, 2, 3]), [3, 2, 1], "Reversed([1, 2, 3]) was incorrect.");
}
```

**Comment by ihristova11** [comment]
@cgranade I would be happy to help with this. :) 
Just wondering if there is a naming convention regarding the test names which you would recommend me to follow?

**Comment by cgranade** [comment]
Thanks for the help. @ihristova11! Following the [Q# style guide](https://docs.microsoft.com/quantum/resources/contributing/style-guide), my suggestion would be to name unit tests implemented by functions after the condition being checked (e.g.: `ReversedIsCorrect` in the above snippet) and unit tests implemented by operations after the action being taken to perform the check, as in the example from `DistinguishabilityTests.qs` below.

One thing to watch out for is that if you use `@Test("QuantumSimulator")` _and_ the name of the test callable ends in `Test`, then the test may get run twice due to both the legacy and attribute-based testing harnesses discovering the test.

Thanks again for the help, and please let me know if there's anything I can answer!

```Q#
@Test("QuantumSimulator")
operation CheckOverlapBetweenPlusAndOne() : Unit {
    let prep1 = ApplyToEachCA(H, _);
    let prep2 = ApplyToEachCA(X, _);

    EqualityWithinToleranceFact(
        EstimateRealOverlapBetweenStates(
            NoOp<Qubit[]>, prep1, prep2, 1, 1000000
        ),
        1.0 / Sqrt(2.0),
        0.02
    );
    EqualityWithinToleranceFact(
        EstimateImagOverlapBetweenStates(
            NoOp<Qubit[]>, prep1, prep2, 1, 1000000
        ),
        0.0,
        0.02
    );
    EqualityWithinToleranceFact(
        0.5,
        EstimateOverlapBetweenStates(
            prep1, prep2, 1, 1000000
        ),
        0.02
    );
}
```
