### ISSUE TITLE
Enhancements to Microsoft.Quantum.Preparation namespace

### ISSUE THREAD

**Issue by msoeken** [microsoft/QuantumLibraries#344]
# Enhancements to Microsoft.Quantum.Preparation namespace

### Deprecated API

_(full signatures for replacements are listed below)_

- ~~`function QuantumROM(targetError: Double, coefficients: Double[])`~~ → `PurifiedMixedState`
- ~~`function QuantumROMQubitCount(targetError: Double, nCoeffs: Int)`~~ → `PurifiedMixedStateRequirements`
- ~~`operation PrepareQubit(basis : Pauli, qubit : Qubit)`~~ → `PreparePauliEigenstate`
- ~~`operation PrepareArbitraryState(coefficients : ComplexPolar[], qubits : LittleEndian)`~~ → `PrepareArbitraryStateCP`
- ~~`function StatePreparationComplexCoefficients(coefficients : ComplexPolar[])`~~ → only as operation `PrepareArbitraryStateCP`
- ~~`function StatePreperationPositiveCoefficients(coefficients : Double[])`~~ → only as operation `PrepareArbitraryStateD`

### New UDTs

```qsharp
newtype MixedStatePreparation = (
    Requirements: MixedStatePreparationRequirements,
    Norm: Double,
    Prepare: ((LittleEndian, Qubit[], Qubit[]) => Unit is Adj + Ctl)
);

newtype MixedStatePreparationRequirements = (
    NTotalQubits: Int,
    (
        NIndexQubits: Int,
        NDataQubits: Int,
        NGarbageQubits: Int
    )
);
```
Note that `Prepare` takes as second parameter an additional `Qubit` register to prepare auxiliary data, e.g., the sign of a coefficient.

#### M.Q.Preparation namespace

- `function PurifiedMixedState(targetError : Double, coefficients : Double[]) : MixedStatePreparation`
   (new name and signature for `QuantumROM`)
- `function PurifiedMixedStateWithData(targetError : Double, coefficients : (Double, Bool[])[]) : MixedStatePreparation`
- `function PurifiedMixedStateRequirements(targetError : Double, nCoefficients : Int) : MixedStatePreparationRequirements`
- `operation PreparePauliEigenstate(basis : Pauli, qubit : Qubit) : Unit`
- `operation PrepareArbitraryStateCP(coefficients : ComplexPolar[], qubits : LittleEndian) : Unit is Adj + Ctl`
- `operation PrepareArbitraryStateD(coefficients : Double[], qubits : LittleEndian) : Unit is Adj + Ctl`
- `function BlochSphereCoordinates(a0 : ComplexPolar, a1 : ComplexPolar) : (ComplexPolar, Double, Double)`

**Update:** As per API review discussions, the term "purified mixed state" is used in the context of this proposal to mean states of the form |ψ⟩ = Σᵢ √𝑝ᵢ |𝑖⟩ |garbageᵢ⟩ specified by a vector of coefficients {𝑝ᵢ}. States of this form can be reduced to mixed states ρ ≔ 𝑝ᵢ |𝑖⟩⟨𝑖| by tracing over the "garbage" register (that is, a mixed state that is diagonal in the computational basis). Similarly, a "purified mixed state with data" refers to a state of the form Σᵢ √𝑝ᵢ |𝑖⟩ |𝑥ᵢ⟩ |garbageᵢ⟩, where each 𝑥ᵢ is a bitstring encoding additional data associated with the register |𝑖⟩.

See https://arxiv.org/pdf/1805.03662.pdf?page=15 for further discussion.

#### M.Q.Convert namespace

- `function DoubleAsComplexPolar(input : Double) : ComplexPolar`

### Prepare purified mixed state and also output sign of coefficient

```qsharp
let coefficients = [3.14, -1.59, -2.65, -3.58];

// extract sign and wrap it into singleton Bool array
let data = Mapped(ConstantArray(1, _), Mapped(LessThanD(_, 0.0), coefficients));

let state = PurifiedMixedStateWithData(10e-2, Zipped(coefficients, data));
let reqs = state::Requirements;
using ((indexQubits, dataQubits, garbageQubits) = (reqs::NIndexQubits, reqs::NDataQubits, reqs::NGarbageQubits)) {
  state::Prepare(LittleEndian(indexQubits), dataQubits, garbageQubits);

  let signQubit = Head(dataQubits);
  // ...
}
```

## Considerations

- Some changes are already implemented as part of #322 
- Previous discussion on these changes in #211 with implementations in #212 (we can reuse parts of these implementations)

**Comment by guenp** [comment]
@msoeken thanks for the proposal! I think it looks good, just some comments/questions:

- Why deprecate `PrepareQubit`? I think it can still be a useful operation to keep.
- I'm in favor of branching out `PrepareArbitraryState` into `PrepareArbitraryStateCP` and `PrepareArbitraryStateD`, however if/when we get discriminated unions (https://github.com/microsoft/qsharp-compiler/issues/406) would we need to refactor these again?
- What is the difference between `PurifiedMixedState` and `PurifiedMixedStateAndSign`?
- Why does `BlochSphereCoordinates` take two `ComplexPolar` values? Does it calculate the difference between the two on the Bloch sphere?

**Comment by cgranade** [comment]
> * I'm in favor of branching out `PrepareArbitraryState` into `PrepareArbitraryStateCP` and `PrepareArbitraryStateD`, however if/when we get discriminated unions ([microsoft/qsharp-compiler#406](https://github.com/microsoft/qsharp-compiler/issues/406)) would we need to refactor these again?

Personally, I'd suggest that bounded polymorphism (https://github.com/microsoft/qsharp-compiler/issues/557) is likely a better approach than DUs for eliminating type suffixes in general across Q# APIs, such that I'd expect similar to apply here as well.

**Comment by guenp** [comment]
@cgranade Ah, yes that would also work, I personally think that syntax looks very complicated, something like `coefficients: Union[ComplexPolar[], Double[])` like in Python seems easier to read/understand. But either way it looks like there will likely be a compiler feature that would simplify operations with type suffixes in the future.

**Comment by cgranade** [comment]
> @cgranade Ah, yes that would also work, I personally think that syntax looks very complicated, something like `coefficients: Union[ComplexPolar[], Double[])` like in Python seems easier to read/understand. But either way it looks like there will likely be a compiler feature that would simplify operations with type suffixes in the future.

As per action items in most recent API review (#368), I've opened up a suggestion for "anonymous" DUs at https://github.com/microsoft/qsharp-compiler/issues/406. That language suggestion would allow for writing Q# types like `ComplexPolar[] | Double[]`; while such types could not be used without deconstruction into cases, they would still provide a lighter-weight solution than named DU cases (e.g.: `newtype Coefficients = Complex : ComplexPolar[] | Real : Double[];`), allowing for removing type suffixes in cases such as `PrepareArbitraryStateCP` and `PrepareArbitraryStateD` without requiring all of the concepts / typeclasses / bounded polymorphism suggestion at https://github.com/microsoft/qsharp-compiler/issues/557.

**Comment by cgranade** [comment]
As a brief update, it looks like @crazy4pi314 has incorporated the anonymous DU suggestion at https://github.com/microsoft/qsharp-compiler/issues/406 into a new language suggestion at https://github.com/microsoft/qsharp-language/issues/51.
