### ISSUE TITLE
I can't access objects of the Numerics package

### ISSUE THREAD

**Issue by geduardo** [microsoft/QuantumLibraries#385]
**Describe the bug**
If I try to use operations, functions, types... of the Numerics library the compiler won't find them.

**To Reproduce**
Try to invoke the operation `DivideI` from the Numerics library with the namespace Microsoft.Quantum.Arithmetic open.

**Expected behavior**
error QS5022: No identifier with the name "DivideI" exists. 

**System information**
 - OS: Windows
- Microsoft.Quantum.Sdk/0.14.2011120240

**Comment by cgranade** [comment]
(BTW, operations and functions that are provided by additional packages should be marked in the API docs as of 0.14, as a new feature.)

**Comment by geduardo** [comment]
Effectively, that's missing:

```
<Project Sdk="Microsoft.Quantum.Sdk/0.14.2011120240">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```

Adding this made it work: 
```
<Project Sdk="Microsoft.Quantum.Sdk/0.14.2011120240">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Quantum.Numerics" Version="0.14.2011120240" />
  </ItemGroup>
</Project>
```
Thanks! I should add this to the docs page :)

**Comment by cgranade** [comment]
Awesome, glad to hear! I think as far as adding to the docs, that was the goal of https://docs.microsoft.com/en-us/quantum/user-guide/libraries/additional-libraries?tabs=tabid-csproj, but it's unfortunately very hard to find in the TOC at the moment.

**Comment by geduardo** [comment]
Yes, I couldn't find that (and I'm partly in charge of those docs so...)... but I could have search better.

I think adding a specific line on each particular library docs reminding this won't hurt. For example, just after this: 
![image](https://user-images.githubusercontent.com/48300381/100687603-e40fc000-3380-11eb-89a0-dfe8861343e7.png)

Adding a note with a link to that page and clarify that they need to include the package in the project.
