### ISSUE TITLE
AllowAtMostNCallsCA non-deterministic failures

### ISSUE THREAD

**Issue by Strilanc** [microsoft/QuantumLibraries#386]
When I create multiple tests using `AllowAtMostNCallsCA`, I get sporadic failures that look like concurrency bugs.

Repro code:

```
    open Microsoft.Quantum.Diagnostics;
    open Microsoft.Quantum.Intrinsic;

    @Test("ResourcesEstimator")
    operation test1() : Unit {
        for (n in 1..100) {
            using (qs = Qubit[n]) {
                within {
                    AllowAtMostNCallsCA(0, CCNOT, "");
                } apply {
                    op(qs[0], qs[1...]);
                }
            }
        }
    }

    @Test("ResourcesEstimator")
    operation test2() : Unit {
        for (n in 1..100) {
            using (qs = Qubit[n]) {
                within {
                    AllowAtMostNCallsCA(0, CCNOT, "");
                } apply {
                    op(qs[0], qs[1...]);
                }
            }
        }
    }

    operation op(control: Qubit, out_target: Qubit[]) : Unit is Adj {
        for (k in 0..Length(out_target)-1) {
            CNOT(control, out_target[k]);
        }
    }
```

# Expected behavior:

Tests pass.

# Actual behavior:

Test fails sometimes, complaining about iterating a list while mutating it or about an empty stack being popped. For example:

```
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Call stack was empty when popped:
System.InvalidOperationException: This operation does not apply to an empty instance.
   at System.Collections.Immutable.ImmutableStack`1.Pop()
   at Microsoft.Quantum.Diagnostics.AllowAtMostNCallsCA`2.Native.<>c__DisplayClass5_0.<get___Body__>b__3(ICallable callable, IApplyData data)
Unhandled exception. System.InvalidOperationException: Stack empty.
[...]
Test Run Failed.
Total tests: 2
     Passed: 1
     Failed: 1
```

and sometimes:

```
Unhandled exception. System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
Unhandled exception. System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
 ---> Microsoft.Quantum.Diagnostics.AllowAtMostNCallsCA [...]
```

**System information**
 - OS: gLinux
 - Version of affected NuGet or PyPI package: Microsoft.Quantum.Sdk/0.13.20111004

**Comment by tcNickolas** [comment]
I've observed similar behavior today with QDK 0.15.2102128881-beta. 
* One exception I got was the `Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.` when running several tests in parallel.
* Another time I got no exception thrown when I expected to get one (and in later runs I did get the expected exception), so I think the operation counter under-counts sometimes.

**Comment by tcNickolas** [comment]
I'm seeing this issue (or a very similar one) again with QDK 0.15.2103133969: the number of prohibited operations reported as non-zero, even though the code definitely doesn't use them within "within - apply" block. In this case two tests run in parallel, one runs much longer than the other, and the shorter one fails quite consistently.

@cgranade, could you take a look? I'd love to use AllowAtMostNCallsCA in the katas, but this behavior seems too unstable.

**Comment by cgranade** [comment]
> @cgranade, could you take a look? I'd love to use AllowAtMostNCallsCA in the katas, but this behavior seems too unstable.

Thanks for the ping; I'll look as soon as I'm able. I suspect it comes down to running the tests in parallel, as you say; would need to be able to scope the handlers used for counting operation calls to which instance of the simulator each operation is called in.
