### ISSUE TITLE
Can ResultArrayAsInt return 0?

### ISSUE THREAD

**Issue by langdon-holly** [microsoft/QuantumLibraries#387]
"Produces a positive integer", but surely if results is all zeros, it should return 0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db98377-dbb2-24bb-79c3-607d827a1fc0
* Version Independent ID: d76a017a-0950-640c-ceda-e7156bd8db55
* Content: [ResultArrayAsInt function - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.convert.resultarrayasint)
* Content Source: [api/qsharp/microsoft.quantum.convert.resultarrayasint.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/api/qsharp/microsoft.quantum.convert.resultarrayasint.md)
* Product: **quantum**
* GitHub Login: @ricardo-espinoza

**Comment by msoeken** [comment]
Good catch, `0` is returned if all results are `Zero`.

**Comment by langdon-holly** [comment]
Yeah, I was reading [https://docs.microsoft.com/en-us/learn/modules/qsharp-create-first-quantum-development-kit/5-random-number-generator](https://docs.microsoft.com/en-us/learn/modules/qsharp-create-first-quantum-development-kit/5-random-number-generator) and got slightly confused by this mistake.
