### ISSUE TITLE
DoubleAsInt should be added to balance out IntAsDouble

### ISSUE THREAD

**Issue by swernli** [microsoft/QuantumLibraries#405]
Right now there exists an `IntAsDouble` function but no `DoubleAsInt`. Instead, we supply mathematical libraries `Truncate`, `Round`, `Ceiling` and `Floor`. However, it might be worth creating a `DoubleAsInt` that captures the common strategy for balance in the API. Note that the function is implemented in qsharp-compiler at https://github.com/microsoft/qsharp-runtime/blob/main/src/Simulation/QSharpFoundation/Convert/Convert.qs#L20.

**Comment by cgranade** [comment]
Deferring as per discussion at microsoft/qsharp-runtime#497; we may need to refine this in the next API review meeting to resolve the tension between `Truncate` and `DoubleAsInt`, as per @bettinaheim's comments.

**Comment by msoeken** [comment]
Closed per microsoft/qsharp-runtime#497
