### ISSUE TITLE
Add new attributes for QIR support

### ISSUE THREAD

**Issue by cgranade** [microsoft/QuantumLibraries#407]
**Is your feature request related to a problem? Please describe.**
As described by @bettinaheim in https://github.com/microsoft/qsharp-runtime/pull/495, it would be helpful to have Q# attributes to mark inline functions and target instructions:

```qsharp
/// # Summary
/// Compiler-recognized attribute used to indicate that a callable should always be inlined.
@Attribute()
newtype Inline = Unit;

/// # Summary
/// Compiler-recognized attribute for usage within target-specific packages 
/// to specify the name of the instruction on the target machine.
@Attribute()
newtype TargetInstruction = String;
```

**Comment by msoeken** [comment]
I would suggest to let the compiler automatically decide when to inline a callable and when not, but have an attribute `@DontInline` to prevent this from happing.

**Comment by cgranade** [comment]
Closing, as corresponding PR has been merged.
