### ISSUE TITLE
API discussion on auto emulation rewrite step

### ISSUE THREAD

**Issue by msoeken** [microsoft/QuantumLibraries#424]
The auto emulation feature (https://github.com/microsoft/qsharp-runtime/pull/514) requires a new public attribute, currently called

```qsharp
@EmulateWith("Alternative", "Simulator")
operation Op() : ...
```

to express that `Op` should be executed as `Alternative` when run in `Simulator`.

This issue should enable discussions on the API for this PR.

**Comment by cgranade** [comment]
Thanks for opening this, @msoeken! It looks from https://github.com/microsoft/qsharp-runtime/pull/514 like the new attribute would be in the Microsoft.Quantum.Core namespace, is that correct?

**Comment by msoeken** [comment]
Yes, that is correct.

**Comment by cgranade** [comment]
As per https://github.com/microsoft/QuantumLibraries/pull/426, this has been approved modulo the changes discussed in that review. Thanks for driving this!
