### ISSUE TITLE
Some cross references not rendering in API docs

### ISSUE THREAD

**Issue by geduardo** [microsoft/QuantumLibraries#436]
I found that some xrefs aren't rendering in the API docs. The ones I found are the articles about applyleoperationonphase operations, but I don't know if it happens in others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47c04b6b-662e-fb90-a58e-79dcb8bbd381
* Version Independent ID: daa39e03-edaa-0f69-df8e-b77aea04d3fd
* Content: [ApplyLEOperationOnPhaseLEA operation - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arithmetic.applyleoperationonphaselea)
* Content Source: [api/qsharp/microsoft.quantum.arithmetic.applyleoperationonphaselea.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.arithmetic.applyleoperationonphaselea.md)
* Product: **quantum**
* GitHub Login: @ricardo-espinoza

**Comment by geduardo** [comment]
@cgranade Could it be because of the lower caps or could be a problem with the inline xrefs?

**Comment by cgranade** [comment]
This was fixed with #435, but we have not yet published updated API docs for the March release containing that fix. Please feel free to reopen if there is a regression.
