### ISSUE TITLE
Example shows double instead of Int

### ISSUE THREAD

**Issue by TheMagicNacho** [microsoft/QuantumLibraries#438]
**Issue** 
 The example does not match the content.

**Discussion** 
Currently the example on the documentation says which implies a Double instead of an integer.
`Message($"{AbsD(314)}");   // 314
Message($"{AbsD(-271)}");  // 271`

**Recommendation:**
The example should read:
`Message($"{AbsI(314)}");   // 314
Message($"{AbsI(-271)}");  // 271`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea66ebf-2ced-052b-a9fb-b6d730da198d
* Version Independent ID: 6dd1c557-d7f0-fc47-b5c0-ac5f9487cd3d
* Content: [AbsI function - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.absi)
* Content Source: [api/qsharp/microsoft.quantum.math.absi.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.math.absi.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by tcNickolas** [comment]
Thank you for reporting this! The PR with the fix is merged, so the fix should propagate to the website with the next release, some time next week.
