### ISSUE TITLE
Minor blunder in the documentation of IndexRange.

### ISSUE THREAD

**Issue by CarloQMontangero** [microsoft/QuantumLibraries#445]
I think that the lines in the example

for (idx in IndexRange(array)) { ... }
for (idx in IndexRange(array)) { ... }

should be something like

for (idx in IndexRange(array)) { ... }
for (idx in 0..Length(array)-1) { ... }

to actually show some relevant equivalence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9ecdd0-7148-3c5c-dbaa-4622451e5222
* Version Independent ID: bc9cffe4-9e42-c331-e8f0-fa5ed8a66cca
* Content: [IndexRange function - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arrays.indexrange)
* Content Source: [api/qsharp/microsoft.quantum.arrays.indexrange.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.arrays.indexrange.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by tcNickolas** [comment]
Thank you for reporting this! The PR with the fix is merged, so the fix should propagate to the website with the next release, some time next week.
