### ISSUE TITLE
Internal Function showing up in API docs

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/QuantumLibraries#454]
Since `_TailMeasurementFunction` starts with an underscore this likely shouldn't be in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfc660d-7f5e-38fa-3edb-c70d3d761e9a
* Version Independent ID: de4c24c3-8a1c-c2be-d7d4-49ae82f44737
* Content: [_TailMeasurement function - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.machinelearning._tailmeasurement)
* Content Source: [api/qsharp/microsoft.quantum.machinelearning._tailmeasurement.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.machinelearning._tailmeasurement.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by cgranade** [comment]
Yep, this is a bug, thanks for catching it!
