### ISSUE TITLE
AddI, SquareI and DivideI not available

### ISSUE THREAD

**Issue by vivienlonde** [microsoft/QuantumLibraries#461]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72d61257-3201-f808-368f-8fc04f720179
* Version Independent ID: 4ac6541f-db66-1480-07e2-252974a2baf2
* Content: [AddI operation - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arithmetic.addi)
* Content Source: [api/qsharp/microsoft.quantum.arithmetic.addi.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.arithmetic.addi.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by vivienlonde** [comment]
Hello,
it seems to me that this operation is not available - even though I opened the Microsoft.Quantum.Arithmetic namespace. I also don't see it in the source code of the arithmetic library. Is it deprecated?
Thank you,
Vivien

**Comment by cgranade** [comment]
As noted at the top of the API reference page for `AddI`, that operation is made available by the Microsoft.Quantum.Numerics package. You can make that package available by adding it to your csproj file, by using `qsharp.packages.add` from a Python host program, or by using the `%package` magic command from IQ#. For more details check out https://docs.microsoft.com/quantum/user-guide/libraries/additional-libraries on the docs site.

Thanks for your question, and please feel free to re-open if there's anything else I can do to help!

**Comment by vivienlonde** [comment]
Indeed, thank you !

**Comment by cgranade** [comment]
Absolutely, no worries. Thanks for the question!
