### ISSUE TITLE
Why does MultiplyI require inputs of equal length?

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumLibraries#465]
The implementation doesn't seem to require inputs x and y of equal length, and it seems to me that it would be convenient to be able to multiply two numbers of length N and M to get a result of length N+M.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32fff831-2b30-3a06-bfc4-94a803f6024f
* Version Independent ID: 313b4ce3-5000-27e1-6a1f-19ecd8481bd5
* Content: [MultiplyI operation - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arithmetic.multiplyi)
* Content Source: [api/qsharp/microsoft.quantum.arithmetic.multiplyi.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.arithmetic.multiplyi.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by msoeken** [comment]
Closed via #568.
