### ISSUE TITLE
Example/use case  please.

### ISSUE THREAD

**Issue by TonyHoldroyd** [microsoft/QuantumLibraries#481]
[Enter feedback here]
I feel that this page and many others, though technically very clear and specific, would be greatly enhanced by the inclusion of a code snippet giving an example and typical use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840b963c-ecc9-2630-f9d9-7c9e0a340baa
* Version Independent ID: c38a7428-510c-8059-5bc6-c5d29ff81589
* Content: [ApplyPauliFromBitString operation - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.canon.applypaulifrombitstring)
* Content Source: [api/qsharp/microsoft.quantum.canon.applypaulifrombitstring.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.canon.applypaulifrombitstring.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by msoeken** [comment]
Thanks @TonyHoldroyd for your comment. I have fixed the particular operation addressed. The many other operations that do not have an example yet will be address through other open issues and general quality improvements.
