### ISSUE TITLE
An error about the Binom function

### ISSUE THREAD

**Issue by QuXing9** [microsoft/QuantumLibraries#498]
## Description

As described in the qsharp [document](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.math.binom)，the function `Binom` computes the binomial coefficient of `n` and `k`. As shown in the below testcase, when the value of the second argument `k` is `zero` or equal to the first argument `n`， the qsharp compiler reports an OverflowException instead of outputting the correct result `1`. I think this may be a bug in the compiler.

## Testcase

~~~c#
namespace NISLNameSpace {
	open Microsoft.Quantum.Intrinsic;
	open Microsoft.Quantum.Math;
	open Microsoft.Quantum.Convert;

	operation NISLOperation() : Unit {
        // when the value of the second argument is 4, it reports the same error 
        mutable NISLVariable2 = Binom(4,0);
        Message(IntAsString(NISLVariable2));
	}

	@EntryPoint()
	operation main() : Unit {
		NISLOperation();
	}
}
~~~

## Output

~~~c#
Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
 ---> NISLNameSpace.NISLOperation on E:\GithubProjects\QuantumFuzzing\src\Fuzzing\qsharpPattern\Program.qs:line 7
   at NISLNameSpace.main on E:\GithubProjects\QuantumFuzzing\src\Fuzzing\qsharpPattern\Program.qs:line 13
~~~

## Expected Output

~~~c#
1
~~~

## Environment

`Operating system`: Windows 10

`dotnet version`: 3.1.414

`QDK`: 0.21.2111177148

### Command

`dotnet run`

**Comment by cgranade** [comment]
Thanks for your report, @QuXing9!

@bettinaheim: Agreed. Looking at the source for `Binom`, this looks to be a duplicate of #506, as `ApproximateFactorial` is called with an argument of `0` when 𝑛 = 0 or 𝑛 = 𝑘. Will add a test case to that effect when fixing #506.
