### ISSUE TITLE
An issue about the Ceiling function

### ISSUE THREAD

**Issue by QuXing9** [microsoft/QuantumLibraries#501]
## Description

As described in the [document](https://docs.microsoft.com/zh-cn/azure/quantum/user-guide/language/typesystem/), qsharp uses 64 bits to store the variable of the type `Int`. Values range from  -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.  The function [`Ceiling`](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.math.ceiling) receives a `Double` argument and returns the smallest integer greater than or equal to the argument. Obviously, the value `922337203685477580` is in the range of the type `Int` and the type `Double`，when passing `922337203685477580.0` to the function `Ceiling`, it returns `922337203685477632` instead of `922337203685477580`. There seems to be a lack of accuracy. Is this a correct output of the function `Ceiling`?

## Testcase

~~~c#
namespace NISLNameSpace {
	open Microsoft.Quantum.Intrinsic;
	open Microsoft.Quantum.Math;

	operation NISLOperation() : Unit {
	    Message($"{Ceiling(922337203685477580.0)}");
	}

	@EntryPoint()
	operation main() : Unit {
		NISLOperation();
	}
}
~~~

## Output

~~~c#
922337203685477632
~~~

## Expected Output

~~~c#
922337203685477580
~~~

## Environment

`Operating system`: Windows 10

`dotnet version`: 3.1.414

`QDK`: 0.21.2111177148

### Command

`dotnet run`

**Comment by msoeken** [comment]
Thanks for reporting this issue @QuXing9. This issue stems from imprecision in the floating-point representation. The output is consistent with the IEEE specification for 64-bit floating points. Other languages will give the same output, e.g., in Python:

```python
from math import ceil
print(ceil(922337203685477580.0))
```

outputs

```
922337203685477632
```
