### ISSUE TITLE
An error about the IntAsBoolArray function

### ISSUE THREAD

**Issue by QuXing9** [microsoft/QuantumLibraries#503]
## Description

The function [IntAsBoolArray](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.convert.intasboolarray) returns a bool array to represent the number `n`. The argument `bits` represents the length of the bool array and the range of `bits` is from 0 to 63. As shown in the below test case, when the value of the argument `bits` is `63`，qsharp reports an error instead of returning an array.

## Testcase

~~~c#
namespace NISLNameSpace {
	open Microsoft.Quantum.Intrinsic;
	open Microsoft.Quantum.Canon;
	open Microsoft.Quantum.Convert;

	operation NISLOperation() : Unit {
		mutable arr = IntAsBoolArray(1, 63);
		Message($"{Length(arr)}");
	}

	@EntryPoint()
	operation main(): Unit {
		NISLOperation();
	}
}
~~~

## Output

~~~c#
Unhandled exception. Microsoft.Quantum.Simulation.Core.ExecutionFailException: `number` must be between 0 and 2^63 - 1, but was 1.
 ---> NISLNameSpace.NISLOperation on C:\Users\10592\Desktop\qsharptest\Program.qs:line 7
   at NISLNameSpace.main on C:\Users\10592\Desktop\qsharptest\Program.qs:line 13        
~~~

## Expected Output

~~~c#
63
~~~

## Environment

`Operating system`: Windows 10

`dotnet version`: 3.1.414

`QDK`: 0.21.2111177148

### Command

`dotnet run`

**Comment by cgranade** [comment]
Thanks for the report, @QuXing6! I can confirm the bug; the root cause is the use of `2^63` within `IntAsBoolArray`, causing `1 < 2^63` to fail.
