### ISSUE TITLE
A suggestion about PNorm/PNormalized function

### ISSUE THREAD

**Issue by QuXing9** [microsoft/QuantumLibraries#505]
When the argument `p` of PNorm/PNormalized is less than 1.0, it reports an error:

```csharp
  Unhandled exception. Microsoft.Quantum.Simulation.Core.ExecutionFailException: PNorm failed. `p` must be >= 1.0
```

But the qsharp [document](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.math.pnormalized) lacks an indication of this condition, I suggest adding it.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 10474636-ba57-8fe5-f80b-78152952a3c5
* Version Independent ID: 2ed46097-0b40-8966-3df9-faa6e6fda821
* Content: [PNorm function - Q# reference - Microsoft Quantum](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.math.pnorm)
* Content Source: [api/qsharp/microsoft.quantum.math.pnorm.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.math.pnorm.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by cgranade** [comment]
Agreed, it would be good to clarify that point in the API documentation, will go on and do so, then. Thanks for your report!
