### ISSUE TITLE
An issue about the ApproximateFactorial function

### ISSUE THREAD

**Issue by QuXing9** [microsoft/QuantumLibraries#506]
Description

As described in the [Microsoft Docs](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.math.approximatefactorial), the function `ApproximateFactorial` returns an approximate factorial of the argument `n`. When `n` is equal to 0, the factorial is 1. As shown in the below test case, `ApproximateFactorial(0)` should return `0.9994942167117412` which is the same as `ApproximateFactorial(1)` instead of `NaN`. Is this a correct behavior of the qsharp language? Looking forward to your reply, Thanks!

## Testcase

```c#
namespace NISLNameSpace {
    open Microsoft.Quantum.Intrinsic;
    open Microsoft.Quantum.Math;

    operation NISLOperation() : Unit {
        Message($"{ApproximateFactorial(0)}");
    }

    @EntryPoint()
    operation main() : Unit {
        NISLOperation();
    }
}
```

## Output

```c#
NaN
```

## Expected Output

```c#
0.9994942167117412
```

## Environment

`Operating system`: Windows 10

`dotnet version`: 3.1.408

`QDK`: 0.21.2111177148

### Command

`dotnet run`

**Comment by cgranade** [comment]
Thanks for raising this, @QuXing9! Looking into it, I can confirm that `ApproximateFactorial(0)` is incorrectly returning `NaN` instead of `0.0` due to the specific approximation being used. Since for small 𝑛, that approximation isn't terribly useful, I think the most straightforward fix is to return exact factorials for small 𝑛. Will go on and get on that, then.

**Comment by QuXing9** [comment]
> Thanks for raising this, @QuXing9! Looking into it, I can confirm that `ApproximateFactorial(0)` is incorrectly returning `NaN` instead of `0.0` due to the specific approximation being used. Since for small 𝑛, that approximation isn't terribly useful, I think the most straightforward fix is to return exact factorials for small 𝑛. Will go on and get on that, then.

Thanks for your reply, @cgranade !
I don't know the implementation algorithm for `ApproximateFactorial`. That is, do the approximation first or do the factorials first.
If doing the factorials first and the fix is to return the exact value, please note that `ApproximateFactorial(0)` should return `1.0` instead of `0.0`. Because the factorial of `0` is `1`.
