### ISSUE TITLE
An issue about the ExpModI function

### ISSUE THREAD

**Issue by QuXing9** [microsoft/QuantumLibraries#512]
## Description

The [ExpModI](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.math.expmodi) function returns x<sup>p</sup> mod N. As shown in the below testcase, when x is `2`, p is `0` and N is `1`, the function returns 1 instead of 0. I think it is a bug of the ExpModI function. 

## Testcase

```c#
namespace NISLNameSpace {
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;
    open Microsoft.Quantum.Math;

    @EntryPoint()
    operation main() : Unit {
        mutable NISLVariable = ExpModI(2,0,1);
        Message($"{NISLVariable}");
    }
}
```

## Output

```
1
```

## Expected Output

```c#
0
```

## Environment

`Operating system`: Windows 10

`dotnet version`: 3.1.408

`QDK`: 0.21.2111177148

### Command

`dotnet run`

**Comment by msoeken** [comment]
@QuXing9, thanks for reporting this issue. It should be resolved once #513 is merged.
