### ISSUE TITLE
Add names to tuple fields of FixedPoint UDT

### ISSUE THREAD

**Issue by msoeken** [microsoft/QuantumLibraries#549]
# Add names to tuple fields of FixedPoint UDT

### Current status

There are currently no tuple field names, which makes it not as easy to access, e.g., the qubit array field.

### New and modified functions, operations, and UDTs

Modify `Microsoft.Quantum.Arithmetic.FixedPoint` UDT as follows:

```qsharp
newtype FixedPoint = (IntegerBits : Int, Register : Qubit[]);
```

### Current status

```qsharp
operation MyOp(fp : FixedPoint) : Unit {
  let register = Snd(fp!);
  // do something with register
}
```

or

```qsharp
operation MyOp(fp : FixedPoint) : Unit {
  let (_, register) = fp!;
  // do something with register
}
```

### Using proposed changes

```qsharp
operation MyOp(fp : FixedPoint) : Unit {
  let register = fp::Register;
  // do something with register
}
```

**Comment by cgranade** [comment]
> ## Proposal
> ### New and modified functions, operations, and UDTs
> Modify `Microsoft.Quantum.Arithmetic.FixedPoint` UDT as follows:
> 
> ```qsharp
> newtype FixedPoint = (integerBits : Int, register : Qubit[]);
> ```

Current style guide suggests using `PascalCase` for UDT names:

```qsharp
newtype FixedPoint = (IntegerBits : Int, Register : Qubit[]);
```

I think that aligns with the examples below as well?

> ### Using proposed changes
> ```qsharp
> operation MyOp(fp : FixedPoint) : Unit {
>   let register = fp::Register;
>   // do something with register
> }
> ```

**Comment by msoeken** [comment]
Thanks for catching this @cgranade. `PascalCase` was indeed intended. It's updated now.
