### ISSUE TITLE
An document error on the Padded function page

### ISSUE THREAD

**Issue by QuXing9** [microsoft/QuantumLibraries#554]
## Description

On the page of the Padded function, the [example](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.arrays.padded#example) is incorrect. As shown below,  the correct call of `padded`  should be `let output = Padded(-6, 2, array);` instead of `let output = Padded(-6, array, 2);`

~~~c#
let array = [10, 11, 12];
// It should be "let output = Padded(-6, 2, array);"
let output = Padded(-6, array, 2);
// It should be "let output = Padded(6, 2, array);"
let output = Padded(6, array, 2);
~~~

**Comment by msoeken** [comment]
Hi @QuXing9, thanks for raising this issue.
