### ISSUE TITLE
New function should be used to match the latest version of QDK

### ISSUE THREAD

**Issue by weucode** [microsoft/QuantumLibraries#563]
When edit the following code in VSCode,this problem appeared:`No identifier with the name "Last" exists`.It is supposed that the `Last` function is replaced by `Tail` function in new version of QDK.

```
ApplyCNOTChainWithTarget(Most(qs), Last(qs));
```

My QDK version is **v0.24.201332**

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e4094915-05f9-3b90-5cbb-933e8351af1f
* Version Independent ID: 3f420867-e21b-f4a0-3b7a-1186419c2550
* Content: [ApplyCNOTChainWithTarget operation - Q# reference - Microsoft Quantum](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.canon.applycnotchainwithtarget)
* Content Source: [api/qsharp/microsoft.quantum.canon.applycnotchainwithtarget.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.canon.applycnotchainwithtarget.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by msoeken** [comment]
Thanks for catching this @weucode
