### ISSUE TITLE
Useless documentation

### ISSUE THREAD

**Issue by FreyaKay** [microsoft/QuantumLibraries#567]
Worst documentation I've ever seen...

How is this useful to anyone? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 276ee443-11a1-cdc4-cb5b-c09cc702f51f
* Version Independent ID: c0abd661-fe40-3a3b-6fae-d67bf602babb
* Content: [R1Frac operation - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.r1frac)
* Content Source: [api/qsharp/microsoft.quantum.intrinsic.r1frac.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.intrinsic.r1frac.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by msoeken** [comment]
Closing due to lack of detailed information. Feel free to file a new issue elaborating on possibilities for improvement.
