### ISSUE TITLE
Conversion functions for signed integers

### ISSUE THREAD

**Issue by msoeken** [microsoft/QuantumLibraries#595]
# Conversion functions for signed integers

## Conceptual overview

Returns Boolean arrays based on two's complement representations of signed integers.

This should be added to the `Numerics` package.

### New and modified functions, operations, and UDTs

```qsharp
namespace Microsoft.Quantum.Convert {

/// # Summary
/// Computes signed integer of two's complement encoding.
function BoolArrayAsSignedInt(bits : Bool[]) : Int { ... }

/// # Summary
/// Computes two's complement encoding as bit array from signed integer
function SignedIntAsBoolArray(number : Int, numBits : Int) : Bool[] { ... }

}
```

## Other functions

The following functions are related and might be discussed in a future API proposal:

```qsharp
namespace Microsoft.Quantum.Convert {

/// # Summary
/// Returns signed integer from bit encoding of unsigned integer
function IntAsSignedInt(number : Int, numBits : Int) : Int { ... }

/// # Summary
/// Returns unsigned integer from bit encoding of signed integer
function SignedIntAsInt(number : Int, numBits : Int) : Int { ... }

}
```

(see also discussion in the comments)

**Comment by tcNickolas** [comment]
This API needs examples to clarify what exactly they do, especially the ones converting between `Int` and `SignedInt`. I find the last two functions a bit confusing, given that Q# `Int` type is signed - I wonder if it makes sense to name them `UnsignedIntAsSignedInt` and `SignedIntAsUnsignedInt`?

**Comment by msoeken** [comment]
That makes sense, however, this will result in some inconsistencies with current APIs, e.g., `BoolArrayAsInt` or `IntAsBoolArray`. I suggest to drop the last two functions for now.

**Comment by msoeken** [comment]
@cgranade remarked during the [June 2022 API review](https://github.com/microsoft/QuantumLibraries/pull/596) that we should coordinate this with the Q# language discussion around bit vectors in general. @swernli and @bettinaheim, could you provide some additional input here.
