### ISSUE TITLE
[Api Reference] Mistake in `ControlledOnInt` and `ApplyControlledOnInt` descriptions

### ISSUE THREAD

**Issue by remilvus** [microsoft/QuantumLibraries#612]
In the API Reference, it's specified that `ControlledOnInt` and `ApplyControlledOnInt` functions should be used with a positive integer, but zero can also be used with these functions. 
I suggest updating their descriptions from:
"(...) if the control register state corresponds to a specified **positive** integer." to
"(...) if the control register state corresponds to a specified **non-negative** integer."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 375e8657-22b1-0aa2-f20a-a34a366254bd
* Version Independent ID: fe542282-6672-45b9-014d-a5152f1fe89e
* Content: [ControlledOnInt function - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-gb/qsharp/api/qsharp/microsoft.quantum.canon.controlledonint)
* Content Source: [api/qsharp/microsoft.quantum.canon.controlledonint.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.canon.controlledonint.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by msoeken** [comment]
Thanks for filing this issue @remilvus. Would you be interested in addressing this issue by creating a PR. I am happy to help.

**Comment by remilvus** [comment]
I can create the PR. Thanks for offering your help, I will ask if any problems arise.

**Comment by remilvus** [comment]
I've managed to do the fix 😃
