### ISSUE TITLE
Example seems to be outdated

### ISSUE THREAD

**Issue by RufusJWB** [microsoft/QuantumLibraries#622]
The example contains the line

```
let op = StatePreparationPositiveCoefficients(amplitudes);
```

I think this line is outdated, as the function `op` is never used in the example and the function `StatePreparationPositiveCoefficients` is marked as deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba3627a-0022-7b7b-7adc-25c25d52ca0f
* Version Independent ID: 70fffdd6-3d8e-330c-d6ac-a7b9a5166f66
* Content: [PrepareArbitraryStateD operation - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.preparation.preparearbitrarystated?source=docs)
* Content Source: [api/qsharp/microsoft.quantum.preparation.preparearbitrarystated.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.preparation.preparearbitrarystated.md)
* Product: **qsharp**
* GitHub Login: @msquantumdocs

**Comment by msoeken** [comment]
Thanks @RufusJWB for flagging this issue. Would you like to create a PR fixing this issue? I am happy to help if there are any questions.

**Comment by RufusJWB** [comment]
> Thanks @RufusJWB for flagging this issue. Would you like to create a PR fixing this issue? I am happy to help if there are any questions.

Of course. Please find the PR here: https://github.com/microsoft/QuantumLibraries/pull/623
