### ISSUE TITLE
Different results appear when running the same program on different OS 

### ISSUE THREAD

**Issue by weucode** [microsoft/QuantumLibraries#624]
# Description

The values of `Sin(PI()/4.0)` are different on Windows and Linux; the former is `0.7071067811865476` and the latter is `0.7071067811865475`.

# Testcase

```
namespace NISLNameSpace {
	open Microsoft.Quantum.Intrinsic;
	open Microsoft.Quantum.Math;
	

	@EntryPoint()
	operation main() : Unit {
		let exptectedProbY = Sin(PI() / 4.0);
		Message($"{exptectedProbY}");
	}
}
```

# Environment

operating system : Windows 10 & Ubuntu 22.04

dotnet version : 6.0.400

QDK : 0.25.228311

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f1d8027c-99e5-76a2-2bc5-65d1f163227e
* Version Independent ID: 6967902d-96dd-c806-ebd1-6cf7a2b2c2a4
* Content: [Sin function - Q# reference - Microsoft Quantum](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.math.sin)
* Content Source: [api/qsharp/microsoft.quantum.math.sin.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.math.sin.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by msoeken** [comment]
Thanks for reporting this issue @weucode. It's not uncommon that different platforms behave slightly different when rounding floating points. It's advised to avoid direct comparison and use error bounds instead.
