### ISSUE TITLE
The implementation of `Sqrt` is inadequate

### ISSUE THREAD

**Issue by weucode** [microsoft/QuantumLibraries#625]
# Description

When giving Sqrt a negative argument, the output is always NaN, but not the actual value.

# Testcase

```
namespace NISLNameSpace {
	open Microsoft.Quantum.Intrinsic;
	open Microsoft.Quantum.Math;
	

	@EntryPoint()
	operation main() : Unit {
		Message($"{Sqrt(-1.0)}");
	}
}
```

# Environment

operating system : Windows 10

dotnet version : 6.0.400

QDK : 0.25.228311

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: aa840a6b-fb85-f4db-a786-e3828f74f3dc
* Version Independent ID: d441b721-c677-3dbb-0be1-b9542d4c3274
* Content: [Sqrt function - Q# reference - Microsoft Quantum](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.math.sqrt)
* Content Source: [api/qsharp/microsoft.quantum.math.sqrt.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.math.sqrt.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by msoeken** [comment]
Thanks for reporting this issue @weucode. The function `Sqrt` is defined on `Double` which is an approximation for real values. Therefore the result of `Sqrt(-1.0)` cannot be represented, except as `NaN`.
