### ISSUE TITLE
The operation matrix is not correct for PauliY gate

### ISSUE THREAD

**Issue by hiroyha1** [microsoft/QuantumLibraries#649]
The operation corresponding to the `PauliY` should be `SH` not `HS`.

https://github.com/microsoft/QuantumLibraries/blob/5cb1f4323e8e81196fdd2a6e07867597c62a9ef2/Standard/src/Preparation/Mixed.qs#L92

```
        } elif (basis == PauliY) {
            H(qubit);
            S(qubit);
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5afabd87-6575-30e6-19e2-12966b80e898
* Version Independent ID: bcbcf3f3-4952-b191-559b-6d9ffd3a4a80
* Content: [PreparePauliEigenstate operation - Q# reference - Microsoft Quantum](https://learn.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.preparation.preparepaulieigenstate)
* Content Source: [api/qsharp/microsoft.quantum.preparation.preparepaulieigenstate.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.preparation.preparepaulieigenstate.md)
* Product: **qsharp**
* GitHub Login: @msquantumdocs

**Comment by msoeken** [comment]
Thanks for filing this, @hirayha1. You are suggesting to change the documentation, right? If you like, you can create a PR to solve this issue. Please let me know if I can help with that.

**Comment by hiroyha1** [comment]
@msoeken 
I created a PR.
