### ISSUE TITLE
Update Broombridge for v0.7 release of chemistry library

### ISSUE THREAD

**Issue by guanghaolow** [microsoft/QuantumLibraries#65]
- Currently Broombridge has fields defined for orbital integral Hamiltonians, and sparse multi-configurational wavefunctions. We need to extend its functionality for describing other interesting formulations of electronic structure problems. See for instance #51 and #58 which introduce unitary coulped-cluster state preparation. What else would be desirable?

- Currently contains a number of fields that are overlapping, not used, and also vague in which fields are used and how. We need reference Broombridge examples that are clearly commented, Unnecessary and inessential information should go into a miscellaneous section.

- While updating Broombridge, we also need to update the json schema for validating the new Broombridge versions.

- See #58, #51 and related. for possible extensions to the next version of Broombridge that is work in progress.

**Comment by cgranade** [comment]
Closing as resolved, since there is no further work for this issue and for Broombridge 0.2. If we need further spec and documentation work for 0.3, let's file that on MicrosoftDocs/quantum-docs-pr.
