### ISSUE TITLE
Specific Broombridge serialization/deserialization tasks

### ISSUE THREAD

**Issue by guanghaolow** [microsoft/QuantumLibraries#73]
Current Broombridge tasks ( see Broombridge directory in gulow/genericladderoperators )

Some specific tasks
- [Reference](https://github.com/Microsoft/QuantumLibraries/pull/58#discussion_r273764934) `public static void SerializeBroombridgev0_2(DataStructures.V0_2.Data data, string filename)`
[ ] "It might be good to serialize to a TextWriter instead so that users can more easily write to MemoryStream instances. Similarly, the deserialization routines might should take TextReaders. In both cases, an overload that takes filenames as in the current behavior would be a very reasonable convienence to provide."

[ ] [Reference](https://github.com/Microsoft/QuantumLibraries/pull/58#discussion_r273765357) Add more property initializers in deserialization.

[ ] #58 Implemented a method for updating deserialized Broombridge filed from v0.1 to newer versions. It would be great to extend this so that the updated Broombridge can be reserializaed back into a file.

**Comment by guenp** [comment]
Hi @cgranade, @msoeken and I believe this issue was already addressed by https://github.com/microsoft/QuantumLibraries/pull/260, is that correct? If yes we will close this ticket.

**Comment by cgranade** [comment]
I think that makes sense, agreed. The rest should be tracked in #279, so this can be safely closed.
